### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by charlax** [utahta/pythonbrew#14]
I guess that to uninstall pythonbrew, we just have to do:

```
rm -Rf ~/.pythonbrew
```

and remove the `source /Users/username/.pythonbrew/etc/bashrc` line in `.bashrc`?

If so, I will add it to the wiki for future reference.

**Comment by oloviv** [comment]
no,  it is not correct at all  if you install at other dir with root.

**Comment by oloviv** [comment]
for example, if you sudo su into root user. and 
export PYTHONBREW_ROOT=/usr/local/pythonbrew
/usr/local/bin/pythonbrew_install

then if you just delete the install directionary only, you will get the followings:

root@lambda:~# /usr/local/bin/pythonbrew_install 
Traceback (most recent call last):
  File "/usr/local/bin/pythonbrew_install", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pythonbrew==1.3.5
