### ISSUE TITLE
pythonbrew fails to install setuptools

### ISSUE THREAD

**Issue by wting** [utahta/pythonbrew#81]
I'm running this on Ubuntu Server 12.04. During installation it fails to build `crypt` and `nis` packages, leading to further problems down the road.

``` console
╭─ting@chibi ~ ‹python-2.7.3›
╰─➤  curl -kL http://xrl.us/pythonbrewinstall | bash
< ... >
╭─ting@chibi ~ ‹python-2.7.3›
╰─➤  [[ -s "$HOME/.pythonbrew/etc/bashrc" ]] && source "$HOME/.pythonbrew/etc/bashrc"
╭─ting@chibi ~ ‹python-2.7.3›
╰─➤  pb install 2.7.3 
Downloading Python-2.7.3.tgz as /home/ting/.pythonbrew/dists/Python-2.7.3.tgz
######################################################################## 100.0%
Extracting Python-2.7.3.tgz into /home/ting/.pythonbrew/build/Python-2.7.3

This could take a while. You can run the following command on another shell to track the status:
  tail -f "/home/ting/.pythonbrew/log/build.log"

Installing Python-2.7.3 into /home/ting/.pythonbrew/pythons/Python-2.7.3
Downloading distribute_setup.py as /home/ting/.pythonbrew/dists/distribute_setup.py
######################################################################## 100.0%
Installing distribute into /home/ting/.pythonbrew/pythons/Python-2.7.3
ERROR: Failed to install setuptools. See /home/ting/.pythonbrew/build.log to see why.
Skip installation of setuptools.

Installed Python-2.7.3 successfully. Run the following command to switch to Python-2.7.3.
  pythonbrew switch 2.7.3
╭─ting@chibi ~ ‹python-2.7.3›
╰─➤  cat ~/.pythonbrew/build.log
cat: /home/ting/.pythonbrew/build.log: No such file or directory
╭─ting@chibi ~ ‹python-2.7.3›
╰─➤  cat ~/.pythonbrew/log/build.log
< ... >
# Substitution happens here, as the completely-expanded BINDIR
# is not available in configure
sed -e "s,@EXENAME@,/home/ting/.pythonbrew/pythons/Python-2.7.3/bin/python2.7," < ./Misc/python-config.in >python-config
Creating directory /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config
Creating directory /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/pkgconfig
/usr/bin/install -c -m 644 Modules/config.c /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config/config.c
/usr/bin/install -c -m 644 Modules/python.o /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config/python.o
/usr/bin/install -c -m 644 ./Modules/config.c.in /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config/config.c.in
/usr/bin/install -c -m 644 Makefile /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config/Makefile
/usr/bin/install -c -m 644 Modules/Setup /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config/Setup
/usr/bin/install -c -m 644 Modules/Setup.local /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config/Setup.local
/usr/bin/install -c -m 644 Modules/Setup.config /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config/Setup.config
/usr/bin/install -c -m 644 Misc/python.pc /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/pkgconfig/python-2.7.pc
/usr/bin/install -c ./Modules/makesetup /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config/makesetup
/usr/bin/install -c ./install-sh /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/config/install-sh
/usr/bin/install -c python-config /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/python2.7-config
rm python-config
./python -E ./setup.py install \
        --prefix=/home/ting/.pythonbrew/pythons/Python-2.7.3 \
        --install-scripts=/home/ting/.pythonbrew/pythons/Python-2.7.3/bin \
        --install-platlib=/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload \
        --root=/
running install
running build
running build_ext
INFO: Can't locate Tcl/Tk libs and/or headers
building 'crypt' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ting/.pythonbrew/pythons/Python-2.7.3/include -I. -IInclude -I./Include -I/usr/local/include -I/home/ting/.pythonbrew/build/Python-2.7.3/Include -I/home/ting/.pythonbrew/build/Python-2.7.3 -c /home/ting/.pythonbrew/build/Python-2.7.3/Modules/cryptmodule.c -o build/temp.linux-i686-2.7/home/ting/.pythonbrew/build/Python-2.7.3/Modules/cryptmodule.o
gcc -pthread -shared build/temp.linux-i686-2.7/home/ting/.pythonbrew/build/Python-2.7.3/Modules/cryptmodule.o -L/home/ting/.pythonbrew/pythons/Python-2.7.3/lib -L/usr/local/lib -o build/lib.linux-i686-2.7/crypt.so
*** WARNING: renaming "crypt" since importing it failed: build/lib.linux-i686-2.7/crypt.so: undefined symbol: crypt
building 'nis' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ting/.pythonbrew/pythons/Python-2.7.3/include -I. -IInclude -I./Include -I/usr/local/include -I/home/ting/.pythonbrew/build/Python-2.7.3/Include -I/home/ting/.pythonbrew/build/Python-2.7.3 -c /home/ting/.pythonbrew/build/Python-2.7.3/Modules/nismodule.c -o build/temp.linux-i686-2.7/home/ting/.pythonbrew/build/Python-2.7.3/Modules/nismodule.o
gcc -pthread -shared build/temp.linux-i686-2.7/home/ting/.pythonbrew/build/Python-2.7.3/Modules/nismodule.o -L/home/ting/.pythonbrew/pythons/Python-2.7.3/lib -L/usr/local/lib -o build/lib.linux-i686-2.7/nis.so
*** WARNING: renaming "nis" since importing it failed: build/lib.linux-i686-2.7/nis.so: undefined symbol: yp_master

Python build finished, but the necessary bits to build these modules were not found:
_bsddb             _curses            _curses_panel   
_sqlite3           _ssl               _tkinter        
bsddb185           bz2                dbm             
gdbm               readline           sunaudiodev     
zlib                                                  
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
crypt              nis                                

running build_scripts
running install_lib
creating /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_bisect.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_codecs_cn.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_codecs_hk.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_codecs_iso2022.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_codecs_jp.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_codecs_kr.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_codecs_tw.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_collections.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_csv.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_ctypes.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_ctypes_test.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_elementtree.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_functools.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_heapq.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_hotshot.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_io.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_json.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_locale.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_lsprof.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_md5.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_multibytecodec.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_multiprocessing.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_random.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_sha.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_socket.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_struct.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/_testcapi.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/array.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/audioop.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/binascii.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/cPickle.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/cStringIO.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/cmath.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/crypt_failed.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/datetime.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/dl.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/fcntl.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/future_builtins.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/grp.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/imageop.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/itertools.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/linuxaudiodev.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/math.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/mmap.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/nis_failed.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/operator.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/ossaudiodev.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/parser.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/pyexpat.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/resource.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/select.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/spwd.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/strop.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/syslog.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/termios.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/time.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
copying build/lib.linux-i686-2.7/unicodedata.so -> /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_bisect.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_codecs_cn.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_codecs_hk.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_codecs_iso2022.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_codecs_jp.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_codecs_kr.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_codecs_tw.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_collections.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_csv.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_ctypes.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_ctypes_test.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_elementtree.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_functools.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_heapq.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_hotshot.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_io.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_json.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_locale.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_lsprof.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_md5.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_multibytecodec.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_multiprocessing.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_random.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_sha.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_socket.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_struct.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/_testcapi.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/array.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/audioop.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/binascii.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/cPickle.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/cStringIO.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/cmath.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/crypt_failed.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/datetime.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/dl.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/fcntl.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/future_builtins.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/grp.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/imageop.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/itertools.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/linuxaudiodev.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/math.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/mmap.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/nis_failed.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/operator.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/ossaudiodev.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/parser.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/pyexpat.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/resource.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/select.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/spwd.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/strop.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/syslog.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/termios.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/time.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/unicodedata.so to 755
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/ to 755
running install_scripts
copying build/scripts-2.7/2to3 -> /home/ting/.pythonbrew/pythons/Python-2.7.3/bin
copying build/scripts-2.7/idle -> /home/ting/.pythonbrew/pythons/Python-2.7.3/bin
copying build/scripts-2.7/pydoc -> /home/ting/.pythonbrew/pythons/Python-2.7.3/bin
copying build/scripts-2.7/smtpd.py -> /home/ting/.pythonbrew/pythons/Python-2.7.3/bin
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/2to3 to 775
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/idle to 775
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/pydoc to 775
changing mode of /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/smtpd.py to 775
running install_egg_info
Writing /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/lib-dynload/Python-2.7.3-py2.7.egg-info
if test -f /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/python -o -h /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/python; \
    then rm -f /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/python; \
    else true; \
    fi
(cd /home/ting/.pythonbrew/pythons/Python-2.7.3/bin; ln -s python2 python)
rm -f /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/python2
(cd /home/ting/.pythonbrew/pythons/Python-2.7.3/bin; ln -s python2.7 python2)
rm -f /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/python2-config
(cd /home/ting/.pythonbrew/pythons/Python-2.7.3/bin; ln -s python2.7-config python2-config)
rm -f /home/ting/.pythonbrew/pythons/Python-2.7.3/bin/python-config
(cd /home/ting/.pythonbrew/pythons/Python-2.7.3/bin; ln -s python2-config python-config)
test -d /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/pkgconfig || /usr/bin/install -c -d -m 755 /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/pkgconfig
rm -f /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/pkgconfig/python2.pc
(cd /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/pkgconfig; ln -s python-2.7.pc python2.pc)
rm -f /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/pkgconfig/python.pc
(cd /home/ting/.pythonbrew/pythons/Python-2.7.3/lib/pkgconfig; ln -s python2.pc python.pc)
Creating directory /home/ting/.pythonbrew/pythons/Python-2.7.3/share/man
Creating directory /home/ting/.pythonbrew/pythons/Python-2.7.3/share/man/man1
/usr/bin/install -c -m 644 ./Misc/python.man \
        /home/ting/.pythonbrew/pythons/Python-2.7.3/share/man/man1/python2.7.1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
Extracting in /tmp/tmpKzaeol
Traceback (most recent call last):
  File "distribute_setup.py", line 494, in <module>
    main(sys.argv[1:])
  File "distribute_setup.py", line 490, in main
    _install(tarball, _build_install_args(argv))
  File "distribute_setup.py", line 73, in _install
    tar = tarfile.open(tarball)
  File "/home/ting/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by onkarnath89** [comment]
I am getting the same error with any version I try using pythonbrew.
But As I do not have admin rights so it is not possible to install these packages. is there a way to install it locally. Installing So many packages one by one manually will be very tedious.
I need pip installed as many of my softwares require many python packages and many other softwares which come through pip. due to this instead of python being installed pip don't install.
Kindly suggest me a solution
